services: 
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: userTasks
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
  app:
    depends_on:
      - db
    ports:
      - 3000:3000
    build: .
    
volumes: 
  dataset: